### ISSUE TITLE
Domains with double quotation marks don't work right

### ISSUE THREAD

**Issue by areynolds15** [Esri/utility-network-properties-extractor#15]
For the Domain Values csv file, any domains that have a double quotation mark (") in the description are not parsed onto separate rows in the csv correctly. Image attached of result. 
![domainProperties](https://user-images.githubusercontent.com/114671267/212335282-be11da43-0205-4456-886f-97edec64102b.png)

**Comment by mhirschheimer** [comment]
Fixed in both the Master and 2.9 branch.  Thanks for pointing this out.
